//Dispatch Alerta 
export const ESPERAR_CARGA = 'ESPERAR_CARGA'
 export const ACTIVAR_ALERTA = 'ACTIVAR_ALERTA'



//Dispatch Conocimientos
export const ACTIVAR_ASIDE = 'ACTIVAR_ASIDE'
export const CONOCIMIENTO_ACTUAL = 'CONOCIMIENTO_ACTUAL'
export const AGREGAR_CONOCIMIENTO='AGREGAR_CONOCIMIENTO'
export const AGREGAR_CARPETA='AGREGAR_CARPETA'
export const HERRAMIENTA_ACTIVADA ='HERRAMIENTA_ACTIVADA'
export const DELETE ='DELETE'
export const EDITAR ='EDITAR'
export const CONFIRMAR_ELIMINACION='CONFIRMAR_ELIMINACION'
export const CARGANDO = 'CARGANDO'
export const CARPETA_ACTUAL = 'CARPETA_ACTUAL'
export const CONOCIMIENTOS_DEFAULT = 'CONOCIMIENTOS_DEFAULT'
export const CARPETAS_DEFAULT = 'CARPETAS_DEFAULT'
export const ERROR = 'ERROR'
export const REINICIO = 'REINICIO'

//Dispatch Usuarios
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_EXITOSO='LOGIN_EXITOSO'
export const CERRAR_SESION ='CERRAR_SESION'
export const MENSAJE = 'MENSAJE'


//Dispatch Proyectos 
export const ACTIVAR_NUEVOPROYECTO = 'ACTIVAR_NUEVOPROYECTO'
export const PROYECTOS_DEFAULT = 'PROYECTOS_DEFAULT'
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO'
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL'
export const DELETE_PROYECTO='DELETE_PROYECTO'
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS'
export const AÑADIR_PROYECTO = 'AÑADIR_PROYECTO'
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO'
